ch07www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from django.urls import reverse



router = DefaultRouter()
router.register(r'profit', views.ProfitViewSet)
router.register(r'music', views.MusicViewSet)
router.register(r'MyoSupplierDT', views.MyoSupplierViewSetDT)
router.register(r'MyoSupplierEx', views.MyoSupplierViewSetEx)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('filer/', include('filer.urls')),
    path('', views.index),
    path('detail/<int:id>', views.detail, name = 'detail-url'),
    path('<int:pid>/<str:del_pass>', views.index),
    path('list/', views.listing),
    path('post/', views.posting),
    path('contact/', views.contact),
    path('post2db/', views.post2db),
    path('captcha/', include('captcha.urls')),
    path('login/', views.login),
    path('logout/', views.logout),
    path('userinfo/', views.userinfo),
    path('diarypost/', views.diarypost),
    path('accounts/', include('registration.backends.default.urls')),
    path('leveltwoinfo/', views.leveltwoinfo),
    path('leveltwoinfo/<int:del_key>/<str:del_product>', views.leveltwoinfo),
    path('leveltwoinfo2/', views.leveltwoinfo2),
    path('leveltwoinfo2/<int:del_key>/<str:del_product>', views.leveltwoinfo2),
    path('people/', views.people),
    path('del_profit/<int:profit_id>/', views.del_profit),
    path('search/', views.search),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('datatable/', views.datatable),
    path('material/', views.material),
    path('addprofit/', views.addprofit),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEIDA_ROOT)

mysite/forms.py
from django import forms
from mysite import models
from captcha.fields import CaptchaField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

class ContactForm(forms.Form):
    CITY = [
        ['TP', 'Taipei'],
        ['TY', 'Taoyuang'],
        ['TC', 'Taichung'],
        ['TN', 'Tainan'],
        ['KS', 'Kaohsiung'],
        ['NA', 'Others'],
    ]
    user_name = forms.CharField(label='您的姓名', max_length=50, initial='李大仁')
    user_city = forms.ChoiceField(label='居住城市', choices=CITY)
    user_school = forms.BooleanField(label='是否在學', required=False)
    user_email = forms.EmailField(label='電子郵件')
    user_message = forms.CharField(label='您的意見', widget=forms.Textarea)
    
    
#8.3模型表單類別ModelForm的應用
class PostForm(forms.ModelForm):
    captcha = CaptchaField() #機器人驗證所需要導入的
    class Meta:
        model = models.Post
        fields = ['mood', 'nickname', 'message', 'del_pass', 'enabled']
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['mood'].label = '現在心情'
        self.fields['nickname'].label = '你的暱稱'
        self.fields['message'].label = '心情留言'
        self.fields['del_pass'].label = '設定密碼'
        self.fields['captcha'].label = '你確定你不是機器人'
        self.fields['enabled'].label = '審核'

class LoginForm(forms.Form):

    username = forms.CharField(label='姓名', max_length=10)
    password = forms.CharField(label='密碼', widget=forms.PasswordInput())
    
    
#寫日記 直接在GFORM上挖一個欄位讓他的輸入格式為 date
#Built-in widgets 要挖其他欄位可以參考下面
# https://docs.djangoproject.com/en/2.1/ref/forms/widgets/#built-in-widgets
class DateInput(forms.DateInput):
    input_type = 'date'
    
class DiaryForm(forms.ModelForm):
    class Meta:
        model = models.Diary
        fields = ['budget', 'weight', 'note', 'ddate']
        widgets = {
            'ddate': DateInput(),
        }
    def __init__(self, *args, **kwargs):
        super(DiaryForm, self).__init__(*args, **kwargs)
        self.fields['budget'].label = '今日花費 (元)'
        self.fields['weight'].label = '今日體重 (KG)'
        self.fields['note'].label = '心情留言'
        self.fields['ddate'].label = '日期'
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['height', 'male', 'website']
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['height'].label = '身高 (cm)'
        self.fields['male'].label = '是男生嗎？'
        self.fields['website'].label = '個人網站'

#把第二層資JJ001透過FORM去做修改利潤的表單
class CategoryLevelTwoForm(forms.ModelForm):
    class Meta:
        model = models.CategoryLevelTwo
        fields = ['name', 'title', 'category', 'image', 'description']
    def __init__(self, *args, **kwargs):
        super(CategoryLevelTwoForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '分類'
        self.fields['title'].label = '中文名稱'
        self.fields['category'].label = '父類別'
        self.fields['image'].label = '商品圖片'
        self.fields['description'].label = '商品描述'
        
class ProfitForm(forms.ModelForm):
    class Meta:
        model = models.Profit
        fields = ['container', 'key', 'value']
    def __init__(self, *args, **kwargs):
        super(ProfitForm, self).__init__(*args, **kwargs)
        self.fields['container'].label = '商品分類'
        self.fields['key'].label = '請輸入數量'
        self.fields['value'].label = '請輸入利潤'
        
class MyoSupplierForm(forms.ModelForm):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'EMAIL請注意格式'}))
    account_contact_email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'EMAIL請注意格式'}))
    class Meta:
        model = models.MyoSupplier
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(MyoSupplierForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '廠商名稱'
        self.fields['company_tax_id'].label = '統一編號'
        self.fields['tel'].label = '公司電話'
        self.fields['fax'].label = '公司傳真'
        self.fields['postal'].label = '3+2郵遞區號'
        self.fields['address'].label = '公司地址'
        self.fields['tax_address'].label = '發票地址'
        self.fields['email'].label = 'EMAIL'
        self.fields['website'].label = '廠商網頁'
        self.fields['contact_sales'].label = '聯絡人'
        self.fields['contact_sales_phone'].label = '聯絡人電話'
        self.fields['contact_sales_mob'].label = '聯絡人手機'
        self.fields['payment'].label = '票期'
        self.fields['bank'].label = '銀行'
        self.fields['transit_number'].label = '銀行代碼'
        self.fields['branch_name'].label = '分行名稱'
        self.fields['branch_id'].label = '分行代碼'
        self.fields['bank_account'].label = '匯款帳號'
        self.fields['account_name'].label = '戶名'
        self.fields['account_contact_name'].label = '帳戶聯絡人'
        self.fields['account_contact_tel'].label = '帳戶聯絡人電話'
        self.fields['account_contact_email'].label = '聯絡人帳戶郵件'
        self.fields['description'].label = '備註'
        #除了name以外的欄位都是非必填 required = False 非必要
        for key in self.fields:
            if key != 'name':
                self.fields[key].required = False

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='form-group col-md-3 mb-0'),
                Column('website', css_class='form-group col-md-3 mb-0'),
                Column('tel', css_class='form-group col-md-3 mb-0'),
                Column('fax', css_class='form-group col-md-3 mb-0'),
                Column('company_tax_id', css_class='form-group col-md-2 mb-0'),
                Column('email', css_class='form-group col-md-3 mb-0'),
                Column('postal', css_class='form-group col-md-2 mb-0'),
                Column('contact_sales', css_class='form-group col-md-2 mb-0'),
                Column('contact_sales_phone', css_class='form-group col-md-3 mb-0'),
                Column('contact_sales_mob', css_class='form-group col-md-3 mb-0'),
                Column('account_contact_email', css_class='form-group col-md-3 mb-0'),
                Column('bank', css_class='form-group col-md-3 mb-0'),
                Column('transit_number', css_class='form-group col-md-2 mb-0'),
                Column('branch_name', css_class='form-group col-md-3 mb-0'),
                Column('branch_id', css_class='form-group col-md-2 mb-0'),
                Column('payment', css_class='form-group col-md-2 mb-0'),
                Column('account_name', css_class='form-group col-md-3 mb-0'),
                Column('bank_account', css_class='form-group col-md-3 mb-0'),
                Column('account_contact_name', css_class='form-group col-md-3 mb-0'),
                Column('account_contact_tel', css_class='form-group col-md-3 mb-0'),
                Column('address', css_class='form-group col-md-6 mb-0'),
                Column('tax_address', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            'description',
        )

class MaterialLevelThreeForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '名稱不能重複'}))
    class Meta:
        model = models.MaterialLevelThree
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(MaterialLevelThreeForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '商品名稱'
        self.fields['myo_supplier'].label = '供應商'
        self.fields['title'].label = '輔助說明'
        self.fields['category'].label = '商品類別'
        self.fields['image'].label = '商品圖片'
        self.fields['description'].label = '商品敘述'
        self.fields['image'].required = False
        self.fields['description'].required = False
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='form-group col-md-3 mb-0'),
                Column('myo_supplier', css_class='form-group col-md-3 mb-0'),
                Column('title', css_class='form-group col-md-3 mb-0'),
                Column('category', css_class='form-group col-md-3 mb-0'),
                Column('image', css_class='form-group col-md-2 mb-0'),
                Column('description', css_class='form-group col-md-3 mb-0'),
                css_class='form-row'
            ),
            'description',
        )

class AddProfitForm(forms.ModelForm):
    class Meta:
        model = models.AddProfitData
        fields = ['container', 'quantity', 'value']
    def __init__(self, *args, **kwargs):
        super(AddProfitForm, self).__init__(*args, **kwargs)
        self.fields['container'].label = '商品分類'
        self.fields['quantity'].label = '請輸入數量'
        self.fields['value'].label = '請輸入利潤'
        #profit = AddProfitData.objects.filter(add_profit=self.add_profit)
    def get_container_fields(self):
        for field_name in self.fields:
            if field_name.startswith('container'):
                yield self[field_name]
            if field_name.startswith('quantity'):
                yield self[field_name]
            if field_name.startswith('value'):
                yield self[field_name]

templates/base.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Datatable -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/b-1.5.6/datatables.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Datatable -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/b-1.5.6/datatables.min.js"></script>


    
    
  </head>
    <title>Django People</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Django People</h1>
          <hr class="mt-0 mb-4">
          {% include "header.html" %}
          {% block content %}{% endblock %}
          {% include "footer.html" %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/contact.html
<!-- contact.html (ch008www object) -->
{% extends "base.html" %}
{% block title %}聯絡管理員{% endblock %}
{% block content %}
{% if message %}
    <div class='alert alert-warning'>{{ message }}</div>
    {% if user_name %}
    {{ user_name }}<br/>
    {{ user_city }}<br/>
    {{ user_school }}<br/>
    {{ user_email }}<br/>
    {{ user_message }}<br/>
    {% endif %}
    無論使用表單提交的數據是什麼，一旦通過調用成功驗證is_valid() <br/>
    （並且is_valid()已經返回True），驗證的表單數據將在form.cleaned_data字典中<br/>
    form = forms.ContactForm(request.POST)<br/>
    if form.is_valid():<br/>
    ....message = "感謝您的來信"<br/>
    ....user_name = form.cleaned_data['user_name']<br/>
    ....user_city = form.cleaned_data['user_city']<br/>
    輕鬆欄位的方式 form = nameForm()<br/>
    安裝寄送MAIL的方式 install django-mailgun
{% endif %}
<div class='container'>
  <div class='panel panel-primary'>
    <div class='panel-heading'>
      <form name='my form' action='.'method='POST'>
      {% csrf_token %}
      <h3>寫信給管理員</h3>
    </div>
    <div class='panel-body'>
      {{ form.as_p }}
    </div>
    <div class='panel-footer'>
      <input type='submit' value='送出'>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/datatable.html
<!-- pos2db.html (ch08www object) -->
{% extends "base.html" %}
{% block title %}商品利潤總覽{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% load static %}
<html lang="en">
<body>
<div class="container">
    <!-- New  button -->
    <div class="text-center">
        <button type="button" data-dismiss="modal" class="btn btn-primary" id="new">新增供應商資料</button>
    </div>
<table id="datatables" class="table table-hover" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>建檔日期</th>
            <th>公司名稱</th>
            <th>統一編號</th>
            <th>聯絡人</th>
            <th>聯絡人電話</th>
            <th>聯絡人手機</th>
            <th>公司地址</th>
            <th>action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>

        </tr>
    </tfoot>
</table>
<!--
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
	开始演示模态框
</button> -->
    <!-- NEW and EDIT Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog" style="width:1000px;">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal_title"></h4>
                </div>
                <div class="modal-body">
                    <form role="form">
                        <div class="form-group">
                            
                                <div class='panel-body'>
                                    {% crispy form %}
                                </div>
                            <div class='panel-footer'>
                                <input type="hidden" id="type" name="type" value="">
                                    <button type="submit" class="btn btn-success btn-block"><span
                                        class="glyphicon glyphicon-ok"></span> OK
                                    </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Modal -->
    <div class="modal fade" id="confirm" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">確定要刪除嗎？</h4>
                </div>
                <div class="modal-body">
                    <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Delete</button>
                    <button type="button" data-dismiss="modal" class="btn">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
<script type="text/javascript">

$(document).ready(function() {
    var table = $('#datatables').DataTable(
    {
    "processing": true,
    "serverSide": true,
    "ajax": {
        "url": "/api/MyoSupplierDT/",
        "type": "GET",
        //"dataSrc":""
    },
    "columnDefs": [
    { "orderable": false, "targets": 8 }
        ],
    "columns": [
        {"data": "id"},
        {"data": "create_time"},
        {"data": "name"},
        {"data": "company_tax_id"},
        {"data": "contact_sales"},
        {"data": "contact_sales_phone"},
        {"data": "contact_sales_mob"},
        {"data": "address"},
        {
            "data": null,
            "defaultContent": '<button type="button" class="btn btn-info" >修改</button>' + '&nbsp;&nbsp' +
            '<button type="button" class="btn btn-danger">刪除</button>'
        }
    ]
});


var id = 0;

$('#datatables tbody').on('click', 'button', function () {
    let data = table.row($(this).parents('tr')).data();
    let class_name = $(this).attr('class');
    if (class_name == 'btn btn-info') {
        // EDIT button
        $('#id_name').val(data['name']);
        $('#id_company_tax_id').val(data['company_tax_id']);
        $('#id_tel').val(data['tel']);
        $('#id_fax').val(data['fax']);
        $('#id_postal').val(data['postal']);
        $('#id_address').val(data['address']);
        $('#id_tax_address').val(data['tax_address']);
        $('#id_email').val(data['email']);
        $('#id_website').val(data['website']);
        $('#id_contact_sales').val(data['contact_sales']);
        $('#id_contact_sales_phone').val(data['contact_sales_phone']);
        $('#id_contact_sales_mob').val(data['contact_sales_mob']);
        $('#id_payment').val(data['payment']);
        $('#id_bank').val(data['bank']);
        $('#id_transit_number').val(data['transit_number']);
        $('#id_branch_name').val(data['branch_name']);
        $('#id_branch_id').val(data['branch_id']);
        $('#id_bank_account').val(data['bank_account']);
        $('#id_account_name').val(data['account_name']);
        $('#id_account_contact_name').val(data['account_contact_name']);
        $('#id_account_contact_tel').val(data['account_contact_tel']);
        $('#id_account_contact_email').val(data['account_contact_email']);
        $('#id_description').val(data['description']);
        $('#modal_title').text('編輯資料');
        $('#type').val('edit');
        $("#myModal").modal();
    } else {
        // DELETE button
        $('#modal_title').text('DELETE');
        $("#confirm").modal();
    }
    id = data['id'];
});

$('form').on('submit', function (e) {
    e.preventDefault();
    let $this = $(this);
    let type = $('#type').val();
    let method = '';
    
    let url = '/api/MyoSupplierDT/';
    if (type == 'new') {
        // new
        method = 'POST';
    } else {
        // edit
        url = url + id + '/';
        method = 'PUT';
    }

    $.ajax({
        url: url,
        method: method,
        data: $this.serialize()
    }).done(function (data, textStatus, jqXHR) {
        location.reload();
    }).fail(function (jqXHR, textStatus, errorThrown) {
        console.log(jqXHR)
    });
});


$('#confirm').on('click', '#delete', function (e) {
    $.ajax({
        url: '/api/MyoSupplierDT/' + id + '/',
        method: 'DELETE'
    }).done(function (data, textStatus, jqXHR) {
        location.reload();
    }).fail(function (jqXHR, textStatus, errorThrown) {
        console.log(jqXHR)
    });
});

$('#new').on('click', function (e) {
    $('#song').val('');
    $('#singer').val('');
    $('#type').val('new');
    $('#modal_title').text('新增資料');
    $("#myModal").modal();
});

});
 </script>

{% endblock %}

templates/footer.html
<!-- footer.html (ch07www object) -->
<hr>
{% load static %}
<img src="{% static 'images/logo.png' %}" width=60>
<button type="submit" class="btn btn-success">Save person</button>
<em> Copyright 2019 <a href='https://myoacg.com/'>https://myoacg.com/</a>. ALL rights reserved.</em>

templates/header.html
<!-- header.html (ch07www object) -->
  <nav class='navbar navbar-default'>
    <div class='container-fluid'>
      <div class='navbar-header'>
        <div class='nav-brand' align=center>
          LEO的測試環境 <br/>
          {% if messages %}
          登入中
          {% endif %}
        </div>
      </div>
      <ul class='nav navbar-nav'>
        <li class='active'><a href='/'>Home</a></li>
        {% if username %}
          <li><a href='/logout'>登出</a><li>
          <li><a href='/list'>瀏覽訊息</a><li>
          <li><a href='/post'>張貼訊息</a><li>
          <li><a href='/post2db'>POST2DB</a><li>
          <li><a href='/contact'>聯絡管理員</a><li>
          <li><a href='/userinfo'>個人資料</a><li>
          <li><a href='/diarypost'>日記</a><li>
        {% else %}
          <li><a href='/login'>登入</a><li>
          <li><a href='/accounts/register'>註冊</a><li>
          <li><a href='/contact'>聯絡管理員</a><li>
        {% endif %}
        <li><a href='/leveltwoinfo'>二層</a><li>
        <li><a href='/leveltwoinfo2'>二層2</a><li>
        <li><a href='/people'>table</a><li>
        <li><a href='/datatable'>供應商</a><li>
        <li><a href='/material'>原物料</a><li>
        <li><a href='/addprofit'>新增利潤</a><li>
        <li><a href='/admin'>後臺管理</a><li>
      </ul>
    </div>
  </nav>

templates/material.html
<!-- mateial.html (ch08www object) -->
{% extends "base.html" %}
{% block title %}商品利潤總覽{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% load static %}
<html lang="en">
<body>
<div class="container">
    <!-- New  button -->
    <div class="text-center">
        <button type="button" data-dismiss="modal" class="btn btn-primary" id="new">新增原物料資料</button>
    </div>
<table id="MaterialLevelThree" class="table table-hover" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>建檔日期</th>
            <th>原料名稱</th>
            <th>輔助說明</th>
            <th>圖片</th>
            <th>action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>

        </tr>
    </tfoot>
</table>
<!--
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
	开始演示模态框
</button> -->
    <!-- NEW and EDIT Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog" style="width:1000px;">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal_title"></h4>
                </div>
                <div class="modal-body">
                    <form role="form">
                        <div class="form-group">
                            
                                <div class='panel-body'>
                                    {% crispy form %}
                                </div>
                            <div class='panel-footer'>
                                <input type="hidden" id="type" name="type" value="">
                                    <button type="submit" class="btn btn-success btn-block"><span
                                        class="glyphicon glyphicon-ok"></span> OK
                                    </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Modal -->
    <div class="modal fade" id="confirm" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">確定要刪除嗎？</h4>
                </div>
                <div class="modal-body">
                    <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Delete</button>
                    <button type="button" data-dismiss="modal" class="btn">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
<script type="text/javascript">

$(document).ready(function() {
    var table = $('#MaterialLevelThree').DataTable(
    {
    "processing": true,
    "serverSide": true,
    "ajax": {
        "url": "/api/MaterialLevelThreeSerializer/",
        "type": "GET",
        //"dataSrc":""
    },
    "columnDefs": [
    { "orderable": false, "targets": 8 }
        ],
    "columns": [
        {"data": "id"},
        {"data": "create_time"},
        {"data": "name"},
        {"data": "title"},
        {"data": "myo_supplier"},
        {"data": "image"},
        {
            "data": null,
            "defaultContent": '<button type="button" class="btn btn-info" >修改</button>' + '&nbsp;&nbsp' +
            '<button type="button" class="btn btn-danger">刪除</button>'
        }
    ]
});


var id = 0;

$('#datatables tbody').on('click', 'button', function () {
    let data = table.row($(this).parents('tr')).data();
    let class_name = $(this).attr('class');
    if (class_name == 'btn btn-info') {
        // EDIT button
        $('#id_name').val(data['name']);
        $('#id_company_tax_id').val(data['company_tax_id']);
        $('#id_tel').val(data['tel']);
        $('#id_fax').val(data['fax']);
        $('#id_postal').val(data['postal']);
        $('#id_address').val(data['address']);
        $('#id_tax_address').val(data['tax_address']);
        $('#id_email').val(data['email']);
        $('#id_website').val(data['website']);
        $('#id_contact_sales').val(data['contact_sales']);
        $('#id_contact_sales_phone').val(data['contact_sales_phone']);
        $('#id_contact_sales_mob').val(data['contact_sales_mob']);
        $('#id_payment').val(data['payment']);
        $('#id_bank').val(data['bank']);
        $('#id_transit_number').val(data['transit_number']);
        $('#id_branch_name').val(data['branch_name']);
        $('#id_branch_id').val(data['branch_id']);
        $('#id_bank_account').val(data['bank_account']);
        $('#id_account_name').val(data['account_name']);
        $('#id_account_contact_name').val(data['account_contact_name']);
        $('#id_account_contact_tel').val(data['account_contact_tel']);
        $('#id_account_contact_email').val(data['account_contact_email']);
        $('#id_description').val(data['description']);
        $('#modal_title').text('編輯資料');
        $('#type').val('edit');
        $("#myModal").modal();
    } else {
        // DELETE button
        $('#modal_title').text('DELETE');
        $("#confirm").modal();
    }
    id = data['id'];
});

$('form').on('submit', function (e) {
    e.preventDefault();
    let $this = $(this);
    let type = $('#type').val();
    let method = '';
    
    let url = '/api/MyoSupplierDT/';
    if (type == 'new') {
        // new
        method = 'POST';
    } else {
        // edit
        url = url + id + '/';
        method = 'PUT';
    }

    $.ajax({
        url: url,
        method: method,
        data: $this.serialize()
    }).done(function (data, textStatus, jqXHR) {
        location.reload();
    }).fail(function (jqXHR, textStatus, errorThrown) {
        console.log(jqXHR)
    });
});


$('#confirm').on('click', '#delete', function (e) {
    $.ajax({
        url: '/api/MyoSupplierDT/' + id + '/',
        method: 'DELETE'
    }).done(function (data, textStatus, jqXHR) {
        location.reload();
    }).fail(function (jqXHR, textStatus, errorThrown) {
        console.log(jqXHR)
    });
});

$('#new').on('click', function (e) {
    $('#song').val('');
    $('#singer').val('');
    $('#type').val('new');
    $('#modal_title').text('新增資料');
    $("#myModal").modal();
});

});
 </script>

{% endblock %}